## Дата и время в Питоне

### Модуль datetime

Импорт модуля и класса datetime

In [ ]:
# импортируем весь модуль
import datetime

# чтобы получить доступ к функции now(), сначала обратимся к модулю, потом к классу
print(datetime.datetime.now())

2024-04-24 14:24:39.418265

In [ ]:
# часто из модуля datetime удобнее импортировать только класс datetime
from datetime import datetime

# и обращаться непосредственно к нему
print(datetime.now())

2024-04-24 14:24:43.392029

Объект datetime и функция `now()`

In [ ]:
# поместим созданный с помощью функции now() объект datetime в переменную cur_dt
cur_dt = datetime.now()
print(cur_dt)

2024-04-24 14:24:48.369861

In [ ]:
# с помощью соответствующих атрибутов выведем каждый из компонентов объекта по отдельности
print(cur_dt.year, cur_dt.month, cur_dt.day, cur_dt.hour, cur_dt.minute, cur_dt.second, cur_dt.microsecond)

2024 4 24 14 24 48 369861

In [ ]:
# также можно посмотреть на день недели
# метод .weekday() начинает индекс недели с нуля, .isoweekday() - с единицы
print(cur_dt.weekday(), cur_dt.isoweekday())

2 3

In [ ]:
# посмотрим на часовой пояс с помощью атрибута tzinfo
print(cur_dt.tzinfo)

None

In [ ]:
# для изменения часового пояса нужно импортировать модуль pytz
import pytz

# выведем текущее время в Москве
dt_moscow = datetime.now(pytz.timezone('Europe/Moscow'))
print(dt_moscow)

2024-04-24 17:28:31.354310+03:00

In [ ]:
# снова посмотрим на атрибут часового пояса
print(dt_moscow.tzinfo)

Europe/Moscow

Timestamp

In [ ]:
# получим timestamp текущего времени с помощью метода .timestamp()
timestamp = datetime.now().timestamp()

In [ ]:
# выведем количество секунд, прошедшее с 01.01.1970 до исполнения кода
print(timestamp)

1713968956.114772

In [ ]:
# вернем timestamp в прежний формат с помощью метода .fromtimestamp()
print(datetime.fromtimestamp(timestamp))

2024-04-24 14:29:16.114772

Создание объекта datetime вручную

In [ ]:
# передадим объекту datetime 20 февраля 1991 года
hb = datetime(1991, 2, 20)
print(hb)

1991-02-20 00:00:00

In [ ]:
# извлечем год с помощью атрибута year
print(hb.year)

1991

In [ ]:
# создадим timestamp
print(datetime.timestamp(hb))

667008000.0

### Преобразование строки в объект datetime и обратно

Строка ➞ datetime через `.strptime()`

In [ ]:
# дана строка с датой 2 декабря 2007 года и временем 12 часов 30 минут и 45 секунд
str_to_dt = '2007-12-02 12:30:45'
type(str_to_dt)

str

In [ ]:
# преобразуем ее в datetime с помощью метода .strptime()
res_dt = datetime.strptime(str_to_dt, '%Y-%m-%d %H:%M:%S')

print(res_dt)
print(type(res_dt))

2007-12-02 12:30:45
<class 'datetime.datetime'>

Datetime ➞ строка через `.strftime()`

In [ ]:
# вначале создадим объект datetime и передадим ему 19 ноября 2002 года
dt_to_str = datetime(2002, 11, 19)
type(dt_to_str)

datetime.datetime

In [ ]:
# преобразуем объект в строку в формате "день недели, месяц число, год"
res_str = datetime.strftime(dt_to_str, '%A, %B %d, %Y')

print(res_str)
print(type(res_str))

Tuesday, November 19, 2002
<class 'str'>

In [ ]:
# .strftime() можно применять непосредственно к объекту datetime
dt_to_str.strftime('%A, %B %d, %Y')

'Tuesday, November 19, 2002'

In [ ]:
# можно и так
datetime.now().strftime('%Y-%m-%d')

'2024-04-24'

In [ ]:
# а еще так
datetime.now().strftime('%c')

'Thu Nov 25 15:11:08 2021'

Форматирование даты и времени через `.strptime()` и `.strftime()`

|Код | Описание | Пример |
| --- | --- | --- |
| `%a` | Сокращенное название дня недели | Sun, Mon, … |
| `%A` | Полное название дня недели | Sunday, Monday, … |
| `%w` | День недели как число, Вс - 0, Пн - 1, ... Сб - 6 | 0, 1, …, 6 |
| `%d` | День месяца в виде числа с нулями | 01, 02, …, 31 |
| `%-d` | День месяца в виде числа без нулей | 1, 2, …, 31 |
| `%b` | Сокращенное название месяца | Jan, Feb, …, Dec |
| `%B` | Полное название месяца | January, February, … |
| `%m` | Месяц в виде числа с нулями | 01, 02, …, 12 |
| `%-m` | Месяц в виде числа без нулей | 1, 2, …, 12 |
| `%y` | Год без века как число с нулями | 00, 01, …, 99 |
| `%-y` | Год без века как число без нулей | 0, 1, …, 99 |
| `%Y` | Год с веком | 1999, 2019, ... |
| `%H` | Час (в 24-часовом формате) в виде числа с нулями | 00, 01, …, 23 |
| `%-H` | Час (в 24-часовом формате) в виде числа без нулей | 0, 1, …, 23 |
| `%I` | Час (12-часовой формат) в виде числа с нулями | 01, 02, …, 12 |
| `%-I` | Час (12-часовой формат) в виде числа без нулей | 1, 2, …, 12 |
| `%p` | AM или PM | AM, PM |
| `%M` | Минуты в виде числа с нулями | 00, 01, …, 59 |
| `%-M` | Минуты в виде числа без нулей | 0, 1, …, 59 |
| `%S` | Секунды в виде числа с нулями | 00, 01, …, 59 |
| `%-S` | Секунды в виде числа без нулей | 0, 1, …, 59 |
| `%j` | День года в виде числа с нулями | 001, 002, …, 366 |
| `%-j` | День года в виде числа без нулей | 1, 2, …, 366 |
| `%c` | Полная дата и время | Sun Nov 21 10:38:12 2021 |
| `%x` | Дата | 11/21/21 |
| `%X` | Время | 10:43:51 |

### Сравнение и арифметика дат

Сравнение дат

In [ ]:
# сравним две даты публикации работ Эйнштейна
date1 = datetime(1905, 6, 30) # "К электродинамике движущихся тел"
date2 = datetime(1916, 5, 11) # Общая теория относительности

In [ ]:
# большей считается более поздняя дата
date1 < date2

True

In [ ]:
# обратное будет признано ложным
date1 > date2

False

Календарный и алфавитный порядок дат

In [ ]:
# если даты записаны в виде строки в формате ГГГГ.ММ.ДД,
# то мы можем их сравнивать, как если бы мы сравнивали объекты datetime

# вначале запишем даты в виде строки и сравним их
'2007-12-02' > '2002-11-19'

True

In [ ]:
# теперь в виде объекта datetime
datetime(2007, 12, 2) > datetime(2002, 11, 19)

True

Промежуток времени и класс timedelta

In [ ]:
# если из большей даты вычесть меньшую, то мы получим временной промежуток между датами
diff = date2 - date1
print(diff)

3968 days, 0:00:00

In [ ]:
# при этом результат будет храниться в специальном объекте timedelta
type(diff)

datetime.timedelta

In [ ]:
# атрибут days позволяет посмотреть только дни
print(diff.days)

3968

In [ ]:
# объект timedelta можно также создать вручную

# для этого вначале импортируем соответствующий класс
from datetime import timedelta

# а затем создадим объект timedelta продолжительностью 1 день
timedelta(days = 1)

datetime.timedelta(days=1)

Арифметика дат

In [ ]:
# смотрите, что получается,
# объединив объекты datetime и timedelta, мы можем "путешествовать во времени"

# допустим сейчас 1 января 2070 года
future = datetime(2070, 1, 1)
future

datetime.datetime(2070, 1, 1, 0, 0)

In [ ]:
# а мы хотим отправиться в 1 января 1900 года, т.е. на 170 лет назад

# сначала просто умножим 365 дней на 170
time_travel = timedelta(days = 365) * 170

# а потом переместимся из будущего в прошлое
past = future - time_travel

# к сожалению, мы немного "не долетим", потому что не учли високосные годы, в которых 366 дней
past

datetime.datetime(1900, 2, 12, 0, 0)

In [ ]:
# мы пролетели 62050 дней
365 * 170

62050

In [ ]:
# но мы уже умеем вычислять точное количество дней (с учетом високосных годов)
datetime(2070, 1, 1) - datetime(1900, 1, 1)

datetime.timedelta(days=62092)

In [ ]:
# теперь снова совершим путешествие во времени, но на этот раз укажем правильное количество дней
time_travel = timedelta(days = 62092)

past = future - time_travel
past

datetime.datetime(1900, 1, 1, 0, 0)

In [ ]:
# иногда бывает удобно воспользоваться циклом while, чтобы создать перечень дат
# например, список праздничных новогодних дней в 2021 году

cur_date = datetime(2021, 1, 1)  # эту дату мы будем выводить
end_date = datetime(2021, 1, 10) # это граница (условие в цикле while)

# пока верно условие
while cur_date <= end_date:

  # выведем cur_date в формате "месяц число, год"
  print(cur_date.strftime('%b %d, %Y'))

  # прибавим к выводимой дате один день
  cur_date += timedelta(days = 1)

Jan 01, 2021
Jan 02, 2021
Jan 03, 2021
Jan 04, 2021
Jan 05, 2021
Jan 06, 2021
Jan 07, 2021
Jan 08, 2021
Jan 09, 2021
Jan 10, 2021

### Дата и обработка ошибок

Конструкция try/except и оператор pass

In [ ]:
# пусть дан список чисел в строковом формате, и мы хотим посчитать их сумму
# предположим, буква "а" попала в список случайно
numbers = ['5', '10', 'a', '15', '10']

# объявим переменную суммы
total = 0

# пройдемся по числам
for number in numbers:

  # попробуем прибавить число к переменной total
  try:
    total += int(number)

  # если же этого сделать не удастся
  except:
    # перейдем к следующему числу
    pass

# выведем сумму
total

40

In [ ]:
# напишем этот же код
total = 0

for number in numbers:
  try:
    total += int(number)
  except:
    # но выведем предупреждение, если число прибавить не удалось
    print(f'Элемент \'{number}\' обработать не удалось')

total

Элемент 'a' обработать не удалось

40

Обработка нескольких форматов дат

In [ ]:
# у нас есть данные по среднемесячной температуре в Нью-Йорке в 2002 году
import pandas as pd
temp = pd.read_csv('temperature.csv')
temp

          Date  Temp
0   2002-01-01  47.1
1      2002-02  50.5
2    2002-03-1  54.9
3      2002-04  66.1
4   2002-05-01  72.7
5      2002-06  83.2
6      2002-07  88.8
7    2002-08-1  87.8
8   2002-09-01  80.2
9   2002-10-01  64.1
10     11-2002  53.9
11  2002-12-01  44.1

In [ ]:
# предположим, проанализировав все форматы дат, мы выявили следующие шаблоны
formats = ['%Y-%m-%d', '%Y-%m-%-d', '%Y-%m']

# создадим счетчик для записей, которые не обработались
counter = 0

# пройдемся в цикле по столбцу Date
for d in temp.Date:

  # затем пройдемся по известным нам форматам
  for format in formats:

    # попробуем, применив каждый из форматов,
    # преобразовать строку с датой в объект datetime
    try:
      print(datetime.strptime(d, format))
      counter += 1

    # если что-то пошло не так
    except:
      # перейдем к следующему формату (второй цикл for) или записи (первый цикл for)
      pass

# посмотрим, сколько записей не обработалось
print('Не обработалось записей:', len(temp) - counter)

2002-01-01 00:00:00
2002-02-01 00:00:00
2002-03-01 00:00:00
2002-04-01 00:00:00
2002-05-01 00:00:00
2002-06-01 00:00:00
2002-07-01 00:00:00
2002-08-01 00:00:00
2002-09-01 00:00:00
2002-10-01 00:00:00
2002-12-01 00:00:00
Не обработалось записей: 1

In [ ]:
# воспользуемся решением "из коробки" библиотеки Pandas
# передадим функции read_csv() параметр parse_dates
temp_parsed = pd.read_csv('temperature.csv', index_col = 'Date', parse_dates = True)
temp_parsed

            Temp
Date
2002-01-01  47.1
2002-02     50.5
2002-03-1   54.9
2002-04     66.1
2002-05-01  72.7
2002-06     83.2
2002-07     88.8
2002-08-1   87.8
2002-09-01  80.2
2002-10-01  64.1
11-2002     53.9
2002-12-01  44.1

In [ ]:
# индекс превратился в объект datetime
type(temp_parsed.index)

pandas.core.indexes.base.Index